# GitHub Pages 配置
# 此文件用于配置GitHub Pages的部署环境
#
# 配置说明：
# 1. 确保仓库是公开的
# 2. 在Settings > Pages中选择"GitHub Actions"作为源
# 3. 工作流会自动处理部署
#
# 部署分支：gh-pages (由GitHub Actions自动创建)
# 访问地址：https://你的用户名.github.io/free-layout-demo
